apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
      app: my-app
      type: front-end


# selector is pulled and mapped from Pod.yaml file.
# kubectl create -f service-NodePort.yaml
# kubectl get services
# curl http://192.168.1.2:30008
