apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: web-pod
      image: ubuntu
      command: ["sleep", "3600']
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]


# capabilities are only supported at the container level and not at the pod level