apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  request:

  usages:
    - digital certificate
    - key encipherment
    - server auth
  groups:
    - system: authenticates
