apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  nodeName: node2


  # you can only mention the 'nodeName' only when the creation time.
