apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding

subjects:
  - name: dev-user
    kind: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  name: developer
  kind: Role
  apiGroup: rbac.authorization.k8s.io