apiVersion: v1
kind: Config
current-context: dev-user@google
cluster:
  - name: my-kube-playground
    name: deployment
    name: production
    name: google

contexts:
  - name: my-kube-playground@my-kube-admin
    name: dev-user@google
    name: prod-user@production

users:
  - name: my-kube-admin
    name: admin
    name: dev-user
    name: prod-user