apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - image: postgres
      name: postgres
      env:
        - name: POSTGRESS_PASSWORD
          value: mysecretpassword

