apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end


# kubectl create -f update.yaml
# kubectl get pods
# kubectl get deployments
# kubectl rollout status deployment.apps/myapp-deployment
#     should see each replica status with "successful rollout".
# kubectl rollout history deployment.apps/myapp-deployment
# kubectl delete


