apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx



# kubectl create -f namespace-pod.yaml
# kubectl create -f namespace-pod.yaml --namespace=dev   (* create under different namespace)
# kubectl get pods

# if you always want the pod to be created under 'dev' environment, under metadata

# apiVersion: v1
# kind: Pod
# metadata:
#  name: myapp-pod
#  namespace: dev
#  labels:
#    name: myapp
#    type: front-end
# spec:
#  containers:
#    - name: nginx-container
#      image: nginx