apiVersion: v1
kind: Service
metadata:
  name: bank-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80

  selector:
    name: myapp
    type: back-end



  # selector : is pulling from pod-definition file
  # kubectl crete -f clusterip-service.yaml
  # kubectl get services

