apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: myapp
    type: front-end


# selector : is pulling from pod-definition file


# kubectl crete -f service-definition.yaml
# kubectl get services
# curl http://192.168.1.2:30008    (* ip address of the node which is to access the server)
