apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  accessModes:
    - ReadWriteMany
  capacity:
     storage: 100Mi
  hostPath:
     path: /pv/log






    # Persistent Volume

 # Volume Name: pv-log
 # Storage: 100Mi
 # Access modes: ReadWriteMany
 # Host Path: /pv/log