apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: ngnix
      image: nginx
  tolerations:
    - key: "spray"
      operator: "Equal"
      value: "mortein"
      effect: "NoSchedule"