
# kubectl taint nodes node-name key-value:taint-effect
# kubectl taint nodes node1 app=blue:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: ngnix-container
      image: nginx
  tolerations:
    - key: '"app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"



