apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

replicas: 3
selector:
  matchLabels:
    type: front-end


# kubectl create -f replicaset-definition.yaml
# kubectl get replicaset
# kubectl get pods

# Change the replicas to 6 in the yaml file, then scale to 6.
#

# kubectl replace -f replicaset-definition.yaml
# kubectl scale --replicas=6 -f replicaset-definition.yaml
# kubectl scale --replicas=6 replicaset myapp-replicaset
#kubectl delete replicaset myapp-replicaset       (*Also deleted all underling PODs)
